# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField()),
                ('respository', models.CharField(max_length=255)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordViolation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('respository', models.CharField(max_length=255)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Awaiting response'), (2, 'No action required'), (3, 'Action taken')])),
                ('commit_hash', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=255)),
                ('author_response', models.TextField()),
            ],
        ),
    ]
