# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20170613_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywordviolation',
            old_name='respository',
            new_name='repository',
        ),
    ]
