# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20170613_1541'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeywordViolation',
            new_name='CheckCommit',
        ),
        migrations.RenameModel(
            old_name='ExcludedRepository',
            new_name='Exclude',
        ),
        migrations.RenameModel(
            old_name='CheckHistory',
            new_name='History',
        ),
        migrations.RenameField(
            model_name='exclude',
            old_name='repository_name',
            new_name='repository',
        ),
    ]
