# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_auto_20170613_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('repository', models.CharField(max_length=255)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Awaiting response'), (2, 'No action required'), (3, 'Action taken')], default=1)),
                ('commit_hash', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_email', models.EmailField(max_length=255)),
                ('author_response', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='History',
            new_name='Repository',
        ),
        migrations.DeleteModel(
            name='CheckCommit',
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'History'},
        ),
    ]
