# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0007_auto_20170615_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='author_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
