# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0008_auto_20170615_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Email address not available - unable to notify'), (1, 'Awaiting response'), (3, 'Resolved: No action required'), (4, 'Resolved: Action taken'), (2, 'Author no longer works for organisation')]),
        ),
        migrations.AlterField(
            model_name='repository',
            name='check_time',
            field=models.DateTimeField(help_text='The last time the github API was queried for this repo.'),
        ),
    ]
