# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0009_auto_20170816_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='check_time',
        ),
        migrations.AddField(
            model_name='repository',
            name='checked',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
