# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0010_auto_20170816_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='hash',
            new_name='commit',
        ),
    ]
