# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0011_auto_20170816_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(max_length=255)),
                ('repository', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='commit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
